### ISSUE TITLE
How to do when serial is /dev/ttyS0

### ISSUE THREAD

**Issue by matthieuAlphonse** [tms0/teleinfo-publisher#25]
Hello, my data is on /dev/ttyS0. I can't edit node-RED to change the serial value.
Why is the serial input value not a setting in .env ?
Or how can I configure it ?

**Comment by tms0** [comment]
Hi,

Did you try to change the device mapping in the docker-compose file ? Something like :
```
devices:
  - "/dev/ttyS0:/dev/ttyAMA0"
```

Regards,
Valentin

**Comment by matthieuAlphonse** [comment]
I'm confused I invert input and output :
"/dev/ttyAMA0:/dev/ttyS0"
Sorry

It works
