### ISSUE TITLE
Heures super creuses.

### ISSUE THREAD

**Issue by cob94440** [tms0/teleinfo-publisher#41]
Bonjour Comment rendre le flow compatible avec les heures super creuses?
Merci d'avance

**Comment by tms0** [comment]
Hello,

Le flow prend toutes les "lignes" d'une trame et les transforme en une clé/valeur de l'objet JSON retourné. Donc normalement la donnée correspondante aux heures super creuses sera présente. Par contre je ne connais pas le nom de cette donnée, et cela dépend aussi si votre compteur est en mode historique ou standard.
