### ISSUE TITLE
MQTT login & password

### ISSUE THREAD

**Issue by Micka41** [tms0/teleinfo-publisher#48]
Bonjour,

Comment fait-on pour renseigner un login et un password pour la connexion MQTT ?

Merci.

**Comment by tms0** [comment]
Hello @Micka41,

Je ne pense pas l'avoir prévu dans le code. Par contre j'ai découvert récemment qu'il existait un projet similaire, et qui a l'air bien mieux maintenu que le miens : https://github.com/fmartinou/teleinfo2mqtt

J'ai prévu de basculer dessus chez moi et je pense que j'archiverais ce projet.

Bonne journée,
Valentin
